### ISSUE TITLE
Tratamento de exceção

### ISSUE THREAD

**Issue by oliveiralex** [JoseVieira1996/CRUD-Clientes#1]
Olá José Vieira, tudo bem? Sou o Alexandre e estou corrigindo a sua atividade.

O Trabalho foi aceito, parabéns! Porém, faltou fazer o tratamento de exceções. Está retornando erro 500 quando é informado um id que não existe. O erro ocorre somente na busca do cliente por id (GET).

Abraço e bons estudos

**Comment by JoseVieira1996** [comment]
Obrigado, Alexandre!

Já vi qual era o problema e apliquei a devida correção.

Abraços.

**Comment by oliveiralex** [comment]
Muito obrigado José Vieira!
Vou encerrar a Issue
